# Generated by Django 5.1.5 on 2025-01-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_chaivarity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='price',
            field=models.CharField(default='Rs. 100', max_length=10),
        ),
    ]
